# Generated by Django 5.0 on 2023-12-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_slug_alter_produto_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_promocinal',
            new_name='preco_promocional',
        ),
    ]
