# Generated by Django 5.0 on 2023-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_preco_promocinal_variacao_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
